image: node:6.11.3

stages:
  - build
  - test
  - deploy

my_job:
  stage: build
  script:
    - echo "my_job"


install:
  stage: build
  script:
    - npm install

run_tests:
  stage: test
  script:
    - npm test
  dependencies:
    - install
