image: node:6.11.3

stages:
  - build
  - test
  - deploy

my_job:
  stage: pre
  script:
    - echo "my_job"


build:install
  script:
    - npm install

test:run_tests:
  script:
    - npm test
  dependencies:
    - build:install
